### ISSUE TITLE
[Request]: Maybe A cloud based lua support and repo like robloux lua executors 

### ISSUE THREAD

**Issue by L7NEG** [Deadlineem/Chronix#3]
### Problem

Just like this ex loadstring(game:HttpGet("https://raw.githubusercontent.com/UltimateMenu/UltimateMenu/refs/heads/main/YimMenu/Ultimate_Menu_For_YimMenu.lua"))

### Solution

Feature

### Reason

To be more easy for just adding or removing features from the script rather than manually upload the new one xD

**Comment by Deadlineem** [comment]
> ### Problem
> Just like this ex loadstring(game:HttpGet("https://raw.githubusercontent.com/UltimateMenu/UltimateMenu/refs/heads/main/YimMenu/Ultimate_Menu_For_YimMenu.lua"))
> 
> ### Solution
> Feature
> 
> ### Reason
> To be more easy for just adding or removing features from the script rather than manually upload the new one xD
> 
> ### Additional context
> _No response_

See these for an updater option for the menu.  You can also probably use a toggle for this if you wish but I wouldn't recommend it unless you add a sleep that is at least 1 hour.  Updating will reload the script in the menu

This is a Chronix only feature, they won't add it into YimMenu

https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-Addon.lua#L44
https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-data.lua#L4425

**Comment by L7NEG** [comment]
> > ### Problem
> > Just like this ex loadstring(game:HttpGet("https://raw.githubusercontent.com/UltimateMenu/UltimateMenu/refs/heads/main/YimMenu/Ultimate_Menu_For_YimMenu.lua"))
> > ### Solution
> > Feature
> > ### Reason
> > To be more easy for just adding or removing features from the script rather than manually upload the new one xD
> > ### Additional context
> > _No response_
> 
> See these for an updater option for your menu addon. You can also probably use a toggle for this if you wish but I wouldn't recommend it unless you add a sleep that is at least 1 hour. Updating will reload the script in the menu
> 
> This is a Chronix only feature, they won't add it into YimMenu
> 
> https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-Addon.lua#L44 https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-data.lua#L4425

Exactly thx for letting me know about it + I just meant that a section in the menu it self where users can just browse the lua they want and gets info about he scripts under a github repo Chronix-Lua

**Comment by Deadlineem** [comment]
> > > ### Problem
> > > Just like this ex loadstring(game:HttpGet("https://raw.githubusercontent.com/UltimateMenu/UltimateMenu/refs/heads/main/YimMenu/Ultimate_Menu_For_YimMenu.lua"))
> > > ### Solution
> > > Feature
> > > ### Reason
> > > To be more easy for just adding or removing features from the script rather than manually upload the new one xD
> > > ### Additional context
> > > _No response_
> > 
> > 
> > See these for an updater option for your menu addon. You can also probably use a toggle for this if you wish but I wouldn't recommend it unless you add a sleep that is at least 1 hour. Updating will reload the script in the menu
> > This is a Chronix only feature, they won't add it into YimMenu
> > https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-Addon.lua#L44 https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-data.lua#L4425
> 
> Exactly thx for letting me know about it + I just meant that a section in the menu it self where users can just browse the lua they want and gets info about he scripts under a github repo Chronix-Lua

I honestly have no clue how to create a Chronix-Lua page like YimMenu has on github, I did have such an Idea but implementing it is the next thing im not sure how to do properly and I just included the script into the menu by default instead.

**Comment by L7NEG** [comment]
> > > > ### Problem
> > > > Just like this ex loadstring(game:HttpGet("https://raw.githubusercontent.com/UltimateMenu/UltimateMenu/refs/heads/main/YimMenu/Ultimate_Menu_For_YimMenu.lua"))
> > > > ### Solution
> > > > Feature
> > > > ### Reason
> > > > To be more easy for just adding or removing features from the script rather than manually upload the new one xD
> > > > ### Additional context
> > > > _No response_
> > > 
> > > 
> > > See these for an updater option for your menu addon. You can also probably use a toggle for this if you wish but I wouldn't recommend it unless you add a sleep that is at least 1 hour. Updating will reload the script in the menu
> > > This is a Chronix only feature, they won't add it into YimMenu
> > > https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-Addon.lua#L44 https://github.com/Deadlineem/Extras_Addon/blob/a800bf153490869aee3ce34192f373290694d85e/Extras-data.lua#L4425
> > 
> > 
> > Exactly thx for letting me know about it + I just meant that a section in the menu it self where users can just browse the lua they want and gets info about he scripts under a github repo Chronix-Lua
> 
> I honestly have no clue how to create a Chronix-Lua page like YimMenu has on github, I did have such an Idea but implementing it is the next thing im not sure how to do properly and I just included the script into the menu by default instead.

Oh to create a Chronix-Lua repo you can just create a free organization on github nammed ChronixMenu or any name you want then just you can move this github repo into it from the repo settings then just create the Chronix-Lua or you can just do it like YimMenu-Lua and just separate it to another organization

**Comment by L7NEG** [comment]
Like github.com/Chronix-Lua

**Comment by L7NEG** [comment]
> Like github.com/Chronix-Lua

Then from there you can do a code to make the section of like browse script and from there it will fetch it

**Comment by Deadlineem** [comment]
@L7NEG Looking into implementing this now, not sure how successful I will be but it will be in the next update if i can get it working properly.

**Comment by L7NEG** [comment]
> @L7NEG Looking into implementing this now, not sure how successful I will be but it will be in the next update if i can get it working properly.

That's great fr + if you can you can just make it on the mrxgta one too

**Comment by Deadlineem** [comment]
> > @L7NEG Looking into implementing this now, not sure how successful I will be but it will be in the next update if i can get it working properly.
> 
> That's great fr + if you can you can just make it on the mrxgta one too

I will try but I highly doubt Mr-X or any of the yim developers are for it. I was kinda bitched out about it which is why I started chronix to begin with.
