### ISSUE TITLE
[Request]: Can you improve player magnet or how can i bring players to my lobby

### ISSUE THREAD

**Issue by MZ1hjZFnZQALmFvP** [Deadlineem/Chronix#4]
### Problem

 Can you improve player magnet or how can i bring players to my lobby

### Solution

.

### Reason

.

### Additional context

.

**Comment by Deadlineem** [comment]
Network > Spoofing > Enable Multiplex and set to 5.

Network > Enable Player Magnet > New Public Session.  This was fixed with 
https://github.com/Deadlineem/Chronix/commit/a4da1fa92158b349e369ce119db9cf0c9081b060
