### ISSUE TITLE
[Improvement]: can you add all benny wheels in ls custom section

### ISSUE THREAD

**Issue by MZ1hjZFnZQALmFvP** [Deadlineem/Chronix#5]
### Which feature

.

### Reason

.

### Additional context

.

**Comment by Deadlineem** [comment]
> ### Which feature
> .
> 
> ### Reason
> .
> 
> ### Additional context
> .

They are, aren't they?  
Wheel Type > Bennys Originals/Bennys Bespoke

Front Wheel > Select Rim Style +/ Select Tire Design

**Comment by MZ1hjZFnZQALmFvP** [comment]
> > ### Which feature
> > .
> > ### Reason
> > .
> > ### Additional context
> > .
> 
> They are, aren't they? Wheel Type > Bennys Originals/Bennys Bespoke
> 
> Front Wheel > Select Rim Style +/ Select Tire Design
