### ISSUE TITLE
[Bug]: FPS drops to 3 when i open the menu it wasnt like this before i update menu any idea why this happens 

### ISSUE THREAD

**Issue by MZ1hjZFnZQALmFvP** [Deadlineem/Chronix#6]
### Describe the bug

.

### Steps To Reproduce

.

### Expected Behavior

.

### Logs

.

### Screenshots / Video

.

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

n

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Deadlineem** [comment]
Is the header image loaded on the menu?

**Comment by MZ1hjZFnZQALmFvP** [comment]
> Is the header image loaded on the menu?

yes its ok when i dont press my hotkey to load the menus it happens only when i press my hotkey to use it

**Comment by Deadlineem** [comment]
> > Is the header image loaded on the menu?
> 
> yes its ok when i dont press my hotkey to load the menus it happens only when i press my hotkey to use it

the header image is not loading, this is bc i updated the site it uses to https so i need to push a quick update

**Comment by MZ1hjZFnZQALmFvP** [comment]
> > > Is the header image loaded on the menu?
> > 
> > 
> > yes its ok when i dont press my hotkey to load the menus it happens only when i press my hotkey to use it
> 
> the header image is not loading, this is bc i updated the site it uses to https so i need to push a quick update

thank you for your great menu i love using it

**Comment by Deadlineem** [comment]
Youre welcome.  It should be fixed within the hour.

**Comment by Yasinislamrony** [comment]
I dont peep any fps drop i peep When the i press insert button game stuck fo' a sec n' fix automatically afta injectin'.

**Comment by Deadlineem** [comment]
> I dont peep any fps drop i peep When the i press insert button game stuck fo' a sec n' fix automatically afta injectin'.

I updated the website the menu loads the header images from to https instead of just http, this causes some issues with the header images that I will address momentarily.

**Comment by Yasinislamrony** [comment]
I dont think dis would be problem game be not crashin' n' not freezin' fo' a while.

**Comment by Deadlineem** [comment]
Updating the menu again now, this will fix the issue.  Give it 20-30 minutes for github workflow to compile the latest dll.
