### ISSUE TITLE
[Bug]: the game crash or freeze every start heist after latest update

### ISSUE THREAD

**Issue by ardypratamaa** [Deadlineem/Chronix#7]
### Describe the bug

the game crash or freeze every start heist after latest update

### Steps To Reproduce

go to any final heist then start heist it will crash

### Expected Behavior

i hope its can be fixed so i can doing some heist again

### Logs

[cout.log](https://github.com/user-attachments/files/18265560/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Deadlineem** [comment]
> ### Describe the bug
> the game crash or freeze every start heist after latest update
> 
> ### Steps To Reproduce
> go to any final heist then start heist it will crash
> 
> ### Expected Behavior
> i hope its can be fixed so i can doing some heist again
> 
> ### Logs
> [cout.log](https://github.com/user-attachments/files/18265560/cout.log)
> 
> ### Screenshots / Video
> _No response_
> 
> ### Store
> Steam
> 
> ### Language
> English
> 
> ### YimMenu Language
> English (US)
> 
> ### Additional context
> _No response_
> 
> ### Build
> * [x]  I've confirmed the issue exists on the latest version of YimMenu
> 
> ### Coload
> * [x]  I've tested this without co-loading anything.

Are you trying to do heists with other players?  If so, this is no longer possible due to the new Battleye implementations in GTA5

**Comment by ardypratamaa** [comment]
i was doing heist with other with FSL also before latest update last nightwith chronix  and its work, if i do heist with mr-x yim version right now its still work but i have to be the host

**Comment by Deadlineem** [comment]
> i was doing heist with other with FSL also before latest update with chronix and its work, if i do heist with mr-x yim version right now its still work but i have to be the host

Does this happen with any heist?

**Comment by ardypratamaa** [comment]
before the Header Issue i think any heist is work and possible, im using apartment rn bcs i want to carry my friend to get 15 mil XD 

the problem is after latest update when i play final heist the game will crash :((

btw, Thanks for the menu mates !!

**Comment by Deadlineem** [comment]
> before the Header Issue i think any heist is work and possible, im using apartment rn bcs i want to carry my friend to get 15 mil XD
> 
> the problem is after latest update when i play finale heist the game will crash :((
> 
> btw, Thanks for the menu mates !!

I will test this right now and get back to you.  Last i knew, heists were not possible anymore due to battleye, it either froze while on the Launching Session screen or Crashed.  Fixing the header issue was a minor update, only changed the header image url to support https, before that the GTAV-Classes tag was updated.

**Comment by ardypratamaa** [comment]
but its not, ur menu still can heist 2 days ago even after 1.70 updates, i was doing many times xD
you can try mr-x yim rn that menu can heist like pacific robbery but using FSL and have to be the host of finale

**Comment by Deadlineem** [comment]
> but its not, ur menu still can heist 2 days ago even after 1.70 updates, i was doing many times xD you can try mr-x yim right now that menu can heist like pacific robbery but using FSL and have to be the host of finale

I just did the pacific standard heist no issue, didn't crash or freeze or anything.

**Comment by ardypratamaa** [comment]
1 more, maybe you can try series A funding, on my game its sadly freeze

**Comment by Deadlineem** [comment]
> 1 more, maybe you can try series A funding, on my game its sadly freeze

Ill try series A after this, just ran a second Pacific with no issues, in the final cutscene now

**Comment by ardypratamaa** [comment]
which menu did you use? the lates nightly update or?
alr if anything work i'll try again, tysm mate !!

**Comment by ardypratamaa** [comment]
ok i found the problem, the problem is every i turn on the BE Server client on settings debug it will make me crash somehow

**Comment by Deadlineem** [comment]
> ok i found the problem, the problem is every i turn on the BE Server client on settings debug it will make me crash somehow

The Battleye Server in Debug is (BETA) and is not for anything other than testing, this was added BEFORE the most recent update (GTA 1.70) and is 100% the reason you are having these issues.  I was not aware anyone even noticed this option lmao
